---
services:
  bot:
    build: .
    # image: jtmb92/ruckus-bot:latest
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=bot
      - MYSQL_PASSWORD=bot_db_password1234!
      - MYSQL_DATABASE=db
      # - REACT_APP_API_URL=http://proxy.branconet.lan:3003
      - BOT_TOKEN=
    ports:
      - "8080:8080"
      - "3003:3003"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
      # - ./config/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=bot
      - MYSQL_PASSWORD=bot_db_password1234!
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - "3306:3306"

volumes:
  mysql_data:
