version: '3'

services:
  bot:
    build:
      context: .
    environment:
      TZ: America/Toronto
      BOT_TOKEN:
      # MYSQL_DATABASE: db
      # MYSQL_USER: user
      # MYSQL_PASSWORD: "password"
      # PUID: 1000
      # PGID: 1000
    ports:
      - '8081:8080'
  # db:
  #   image: mysql:5.7
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: 'db'
  #     MYSQL_USER: 'user'
  #     MYSQL_PASSWORD: 'password'
  #     MYSQL_ROOT_PASSWORD: 'password'
  #   ports:
  #     - '3306:3306'
  #   volumes:
  #     - /temp/db:/var/lib/mysql
  # phpmyadmin:
  #   image: phpmyadmin
  #   restart: always
  #   ports:
  #     - 8082:80
  #   environment:
  #     - PMA_ARBITRARY=1
