# Stage 2: Serve nginx
FROM nginx:alpine
COPY dashboard /usr/share/nginx/html
COPY config/nginx.conf /etc/nginx/nginx.conf
COPY config/conf.d /etc/nginx/conf.d/

# Stage 1: Build React App
FROM node:16-alpine AS build
WORKDIR /app
COPY /bot ./bot
RUN cd bot && \
    npm install && \
    npm install -g nodemon  

# Install Supervisor
RUN apk add --no-cache supervisor

# Copy Supervisor configuration
COPY config/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Expose port 8080
EXPOSE 8080

# Start Supervisor to manage services
CMD ["supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
